### ISSUE TITLE
User registration not visible

### ISSUE THREAD

**Issue by Ankit6098** [Singh233/Social-React-App#2]
I am trying to register for an account on this repository, but I am unable to find the registration option. I have searched through the repository and looked at the documentation, but I haven't found any information on how to register.

Can someone please help me with this issue? It would be very helpful if the registration process could be made more visible for new users.

Thank you.

**Comment by Singh233** [comment]
I appreciate your interest in my repository. I apologize for any confusion caused by the lack of a registration option.

At this time, I have not opened registration for this repository. I am currently working on developing a registration system and hope to make it available in the near future.

I appreciate your patience and understanding as I work to improve the user experience for our repository. If you have any further questions or concerns, please don't hesitate to let me know.

Best regards,
Sanambir Singh

**Comment by Singh233** [comment]
The issue is resolved now. Sign up feature is visible and fully functional. 🚀
